name: My first workflow

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List and read file
      run: |
        echo "My first github action Job"
        ls -ltrha
        cat README.md  
    

    - name: Generate ASCIII artwork 
      run: cowsay -f dragon "Run for cover, I am a dragong RAWR"   >> dragon.txt  