name: Generate Ascii artwork

on: push

jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List and read file
      run: |
        echo "My first github action Job"
        ls -ltrha
        cat README.md  

    # - name: Checkout Repo files
    #   run: grep -i dragon ascii-script.sh    

    - name: Executing Shell script
      run: |
        chmod +x .github/workflows/ascii-script.sh  
        .github/workflows/ascii-script.sh  

    