name: Generate Ascii artwork

on: push

jobs: 
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List and read file
      run: |
        echo "My first github action Job"
        ls -ltrha
        cat README.md  

    - name: Install cowsay program
      run: sudo apt-get install cowsay -y   

    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a dragong RAWR"   >> dragon.txt  

    - name: Test file exist
      run: grep -i "dragon" dragon.txt

    - name: Read File
      run: cat dragon.txt 
      
    - name: Checkout Repo files
      run: ls -ltrha  